name: Actualizar resumen de cambios

on: [push] 

permissions:
  contents: write  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Agregar resumen de cambios
        run: |
          echo "## Última actualización: $(date)" >> README.md

      - name: Commit y push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Actualizar resumen de cambios" || echo "Sin cambios que guardar"
          git push
